services:
  l1jdb:
    image: mariadb:10.2
    container_name: l1j-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: l1jdb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - my-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - l1jnet

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: l1j-phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8081:80" # remove it if you use ssl to acces through nginx (more info in nginx.conf)
    environment:
      PMA_HOST: l1jdb
    depends_on:
      - l1jdb
    networks:
      - l1jnet

  l1jserver:
    environment:
      DB_URL: "jdbc:mysql://l1jdb:3306/l1jdb?autoReconnect=true&useUnicode=True&characterEncoding=UTF-8"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    build: .
    container_name: l1j-server
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/l1j/config
    depends_on:
      - l1jdb
    networks:
      - l1jnet

  nginx:
    image: nginx:latest
    container_name: l1j-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2000:2000"   # proxy login port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/certs:/etc/letsencrypt
    depends_on:
      - l1jserver
      - phpmyadmin
    networks:
      - l1jnet

  certbot:
    image: certbot/certbot
    container_name: l1j-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/certs:/etc/letsencrypt
    networks:
      - l1jnet

volumes:
  my-db:

networks:
  l1jnet:
    driver: bridge
